Add links to Ethical Web Principles
w3ctag/design-principles pull request #295
Opened 2021-03-08 22:30 UTC by rhiaro

Links to Ethical Web Principles from the abstract and section 1 intro, for #282

2021-04-13 08:21 UTC, torgo requested changes
consistency in use of [[reference]] - otherwise gtg

2021-04-13 09:06 UTC, hadleybeeman approved these changes
Looks good to me!

2021-04-13 09:21 UTC, cynthia commented on index.bs
> +
We introduced more aggressive line breaking during a rewrite of this document, would it be possible to break the lines following that convention?

(The rationale was to make diffs easier to follow, but also to make it easier to read)

2021-04-14 15:16 UTC, cynthia approved these changes
LGTM!

2021-04-14 15:17 UTC, cynthia commented
Awating on @torgo 's change request. (Has that been done?)

2021-04-14 15:21 UTC, torgo approved these changes

2021-04-14 15:22 UTC, merged