Make naming consistent about methods and arguments. Resolves #195.
w3ctag/design-principles pull request #312
Opened 2021-05-13 00:10 UTC by cynthia

Rename functions->methods (where appropriate) and parameters->arguments.

2021-05-13 00:48 UTC, plinss commented on index.bs
> +If an API methods needs to be asynchronous, use Promises,
```suggestion
If an API method needs to be asynchronous, use Promises,
```

2021-05-13 00:48 UTC, plinss commented on index.bs
> +    make sure that the API methods well when the user can't access the remote server
```suggestion
    make sure that the API functions well when the user can't access the remote server
```

2021-05-13 00:51 UTC, plinss requested changes
Change suggestions inline

2021-05-18 01:13 UTC, plinss approved these changes

2021-05-18 01:15 UTC, atanassov approved these changes

2021-05-18 01:15 UTC, merged