New principle: Identity on the web
w3ctag/design-principles pull request #396
Opened 2022-09-05 16:45 UTC by rhiaro

2022-09-05 16:48 UTC, rhiaro commented on index.bs
> +* The same data is not always appropriate for different scenarios, or in different contexts, so [do not collect more than needed](https://w3ctag.github.io/privacy-principles/#identity) for the servic
TODO: link this properly as a reference

2022-09-06 08:47 UTC, rhiaro commented
We talked about this in Breakout C today, and concluded it's long. We can shorten it by taking care to constrain the scope to architectural things, and focus on what really does and doesn't belong in the Design Principles document. Feedback from @LeaVerou and @cynthia would be particularly helpful on this front.

2023-01-17 05:08 UTC, martinthomson reviewed
It's possible that the framing of this as an "identity layer" is the problem.  The concept of identity in the privacy principles is a good one, as it is the all-encompassing notion of how a user presents in a given context.  It doesn't really get down to the level of detail that this appears to want to.

A more useful framing might be the use of identifiers and the data that is then associated with identifiers.  Identifiers as a handle for identity are the locus of most privacy problems as they concretely engage with recognition (all forms: same-context and cross-context; and for any subjective understanding of that distinction).

Of course, the problem with this is that identity is a broad concept.  It might be that the advice here doesn't really belong in a single principle at this level.  The [ethical web principles item on control](https://www.w3.org/TR/ethical-web-principles/#control), that is referenced in the preceding section, is a better expression of the underlying principles.

2023-01-17 05:08 UTC, martinthomson commented on index.bs
> +* The same data is not always appropriate for different scenarios, or in different contexts, so [do not collect more than needed](https://w3ctag.github.io/privacy-principles/#identity) for the servic
I think that you mean https://w3ctag.github.io/privacy-principles/#data-minimization

But then, I don't know who is collecting in this context.  Presumably the designers of Web APIs.  But they don't collect data, they are more often involved in the supply of data.

2024-01-24 09:52 UTC, cynthia commented on index.bs
> +
```suggestion
```

2024-01-25 02:44 UTC, martinthomson reviewed
A missing point that occurs to me is that identifiers will often be attached to user agents (or really how that user agent presents itself to a site: think IP address or state partitioning) as a proxy for a person.  In effect, the distinction between a person and how they present themselves can be important, but it is often conflated.  So we need to apply the same protections to these proxies as we would the people they model.

2024-01-25 14:32 UTC, torgo commented on index.bs
> +For such features, you should [understand the context](https://w3ctag.github.io/privacy-principles/#identity)
```suggestion
For such features, you should [understand the context]([[PRIVACY-PRINCIPLES#identity]])
```

2024-01-25 14:33 UTC, torgo commented on index.bs
> +[the smallest amount of data](https://w3ctag.github.io/privacy-principles/#data-minimization)
```suggestion
[the smallest amount of data]([[PRIVACY-PRINCIPLES#data-minimization]])
```

2024-01-25 16:08 UTC, rhiaro commented on index.bs
> +For such features, you should [understand the context](https://w3ctag.github.io/privacy-principles/#identity)
```suggestion
For such features, you should [understand the context](https://www.w3.org/TR/privacy-principles/#identity)
```

2024-01-25 16:08 UTC, rhiaro commented on index.bs
> +[the smallest amount of data](https://w3ctag.github.io/privacy-principles/#data-minimization)
```suggestion
[the smallest amount of data](https://www.w3.org/TR/privacy-principles/#data-minimization)
```

2024-01-25 16:45 UTC, cynthia requested changes

2024-01-25 16:45 UTC, cynthia commented on index.bs
> +and be transparent about it.
Active tone would be preferred, along with brevity.

2024-01-25 16:45 UTC, cynthia commented on index.bs
> +
```suggestion
```

2024-01-25 16:46 UTC, cynthia approved these changes

2024-01-31 16:29 UTC, torgo approved these changes

2024-03-06 08:49 UTC, merged

2024-03-06 20:23 UTC, martinthomson reviewed
A belated approval from me.